export const ROUTES = {
  HOME: '/',
  SERVICES: '/services',
  SERVICE_DETAIL: '/services/:slug',
  ABOUT: '/about',
  CAREERS: '/careers',
  CONTACT: '/contact',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:id',
  CASE_STUDIES: '/case-studies',
  LOGIN: '/login',
  ADMIN: '/admin',
  ADMIN_IMAGES: '/admin/images',
  ADMIN_CONTACTS: '/admin/contacts',
  ADMIN_CONTENT: '/admin/content',
  ADMIN_STATS: '/admin/stats',
  ADMIN_CERTS: '/admin/certs',
  ADMIN_TESTIMONIALS: '/admin/testimonials',
  ADMIN_CASE_STUDIES: '/admin/case-studies',
  ADMIN_BLOG: '/admin/blog',
  ADMIN_SERVICES: '/admin/services',
  ADMIN_CULTURE: '/admin/culture',
  NOT_FOUND: '*',
} as const;
